 name: deploy

 on: [push]

 jobs:
   build:

     runs-on: ubuntu-latest
    
     steps:
     - name: executing remote ssh commands using key
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         script: git pull; git submodule update --init --recursive; hugo; cp -r ./public/* /home/gh_actions/server/hugo_site/.; rm -rf ./public
